[build]
  publish = "apps/box-shadow/dist/"
  command = "turbo run build --filter @juanmsl/box-shadow"
  base = "/"

[build.environment]
  YARN_FLAGS = "--frozen-lockfile"
  YARN_VERSION = "1.22.21"
  NODE_VERSION = "20.11.0"

[[redirects]]
  from = "https://juanmsl-box-shadow.netlify.app/*"
  to = "https://box-shadow.juanmsl.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

