export const ENV = {
  CONTENT_FULL_ENVIRONMENT: `${import.meta.env.VITE_APP_CONTENT_FULL_ENVIRONMENT}`,
  API_URL: `${import.meta.env.VITE_APP_BACKEND_URL}`,
  CONTENT_FULL_API_SPACE_ID: `${import.meta.env.VITE_APP_CONTENT_FULL_SPACE_ID}`,
  CONTENT_FULL_API_ACCESS_TOKEN: `${import.meta.env.VITE_APP_CONTENT_FULL_ACCESS_TOKEN}`,
  ASSET_ID_CV: `${import.meta.env.VITE_APP_ASSET_ID_CV}`,
  ASSET_ID_BACKGROUND: `${import.meta.env.VITE_APP_ASSET_ID_BACKGROUND}`,
  ASSET_ID_PROFILE_PICTURE: `${import.meta.env.VITE_APP_ASSET_ID_PROFILE_PICTURE}`,
  GOOGLE_ANALYTICS: `${import.meta.env.VITE_APP_GOOGLE_ANALYTICS}`,
  GOOGLE_TAG_MANAGER: `${import.meta.env.VITE_APP_GOOGLE_TAG_MANAGER}`,
};
