[build]
  publish = "apps/css-tools/dist/"
  command = "turbo run build --filter @juanmsl/css-tools"
  base = "/"

[build.environment]
  YARN_FLAGS = "--frozen-lockfile"
  YARN_VERSION = "1.22.21"
  NODE_VERSION = "20.11.0"

[[redirects]]
  from = "https://juanmsl-css-tools.netlify.app/*"
  to = "https://css-tools.juanmsl.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

