[build]
  publish = "apps/landing-ui/dist/"
  command = "turbo run build --filter @juanmsl/landing-ui"
  base = "/"

[build.environment]
  YARN_FLAGS = "--frozen-lockfile"
  YARN_VERSION = "1.22.21"
  NODE_VERSION = "20.11.0"

[[redirects]]
  from = "https://juanmsl-landing-ui.netlify.app/*"
  to = "https://ui.juanmsl.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

